# Generated by Django 5.2.8 on 2025-11-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_book"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["sort_order"]},
        ),
        migrations.AddField(
            model_name="book",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
